/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2017-07-24 08:32:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1500868533392L));
    _jspx_dependants.put("jar:file:/E:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/e-Nature/WEB-INF/lib/spring-webmvc-4.3.8.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1492505852000L));
    _jspx_dependants.put("jar:file:/E:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/e-Nature/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1500868434285L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1500435569284L));
    _jspx_dependants.put("jar:file:/E:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/e-Nature/WEB-INF/lib/spring-webmvc-4.3.8.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1492505852000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.8.RELEASE.jar", Long.valueOf(1500282486995L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fform_0026_005fmodelAttribute_005fmethod_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005finput_0026_005ftype_005fplaceholder_005fpath_005fclass_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fform_0026_005fmodelAttribute_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005finput_0026_005ftype_005fplaceholder_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fform_0026_005fmodelAttribute_005fmethod_005faction.release();
    _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005ff_005finput_0026_005ftype_005fplaceholder_005fpath_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css-file/carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css-file/social-icon.css\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-inverse\" role=\"navigation\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("    <!--    <a class=\"navbar-brand\" href=\"#\">e-NATURE</a>-->\r\n");
      out.write("      <img src=\"resources/images/logo1.jpg\" style=\"width:30%;height:30%\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ==============Collect the nav links ==========================-->\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li class=\"active\"></li>\r\n");
      out.write("        <li ><a href=\"index\">Home</a></li>\r\n");
      out.write("        \r\n");
      out.write("        <!--dropdown option for products -->\r\n");
      out.write("        <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Product Category<span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("          <li><a href=\"#\">Orchids Plants</a></li>\r\n");
      out.write("          <li><a href=\"#\">Rose Plants</a></li>\r\n");
      out.write("          <li><a href=\"#\">Marigold Plants</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("        <li><a href=\"contactus\">Contact Us</a></li>\r\n");
      out.write("         <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("         <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adding\">Admin</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      <!-- =================Right-align navigation bar================ -->\r\n");
      out.write("     <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\"><span class=\"glyphicon glyphicon-user\"></span> Register</a></li>\r\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goToLogin\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("      <!-- ==================End================================================ -->\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </div><!-- /.navbar-collapse -->\r\n");
      out.write("  </div><!-- /.container-fluid -->\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, intial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css-file/register.css\">\r\n");
      out.write("<title>Registration</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1>Registration Form</h1>\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_f_005fform_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("<div>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css-file/carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css-file/social-icon.css\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"social-icon.css\"> -->\r\n");
      out.write("<title>Footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--=========================== Bottom navbar========================== -->\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-bottom\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("    <!--   <li class=\"active\"><a href=\"#\">About Us</a></li> -->\r\n");
      out.write("      <a href=\"#\" class=\"fa fa-facebook\"></a>\r\n");
      out.write("\t  <a href=\"#\" class=\"fa fa-twitter\"></a>\r\n");
      out.write("\t  <a href=\"#\" class=\"fa fa-google\"></a>\r\n");
      out.write("\t  <a href=\"#\" class=\"fa fa-linkedin\"></a>\r\n");
      out.write("\t  <a href=\"#\" class=\"fa fa-youtube\"></a>\r\n");
      out.write("      <a href=\"#\" class=\"fa fa-instagram\"></a>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- ===========================End===================================== -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_f_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005ff_005fform_0026_005fmodelAttribute_005fmethod_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_f_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005fform_005f0.setParent(null);
    // /WEB-INF/views/register.jsp(35,3) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005fform_005f0.setModelAttribute("user");
    // /WEB-INF/views/register.jsp(35,3) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005fform_005f0.setAction("saveregister");
    // /WEB-INF/views/register.jsp(35,3) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005fform_005f0.setMethod("post");
    int[] _jspx_push_body_count_f_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_f_005fform_005f0 = _jspx_th_f_005fform_005f0.doStartTag();
      if (_jspx_eval_f_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<label>Name</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_f_005finput_005f0(_jspx_th_f_005fform_005f0, _jspx_page_context, _jspx_push_body_count_f_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<label>Password</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_f_005finput_005f1(_jspx_th_f_005fform_005f0, _jspx_page_context, _jspx_push_body_count_f_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<label>Address</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_f_005finput_005f2(_jspx_th_f_005fform_005f0, _jspx_page_context, _jspx_push_body_count_f_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<label>Email</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_f_005finput_005f3(_jspx_th_f_005fform_005f0, _jspx_page_context, _jspx_push_body_count_f_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<label>Phone NO.</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_f_005finput_005f4(_jspx_th_f_005fform_005f0, _jspx_page_context, _jspx_push_body_count_f_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</div>\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Add user\">\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<!-- <button type=\"button\" class=\"btn btn-lg btn-info\">Submit</button> -->\r\n");
          out.write("\t\t\t\t\t\t\t<!-- <button type=\"reset\" class=\"btn btn-lg btn-info\">Reset</button>\t -->\t\t\t\t\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_f_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_f_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_f_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_f_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005ff_005fform_0026_005fmodelAttribute_005fmethod_005faction.reuse(_jspx_th_f_005fform_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_f_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_f_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_f_005finput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fform_005f0);
    // /WEB-INF/views/register.jsp(46,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005finput_005f0.setPath("name");
    // /WEB-INF/views/register.jsp(46,8) null
    _jspx_th_f_005finput_005f0.setDynamicAttribute(null, "placeholder", "Enter Name Here..");
    // /WEB-INF/views/register.jsp(46,8) null
    _jspx_th_f_005finput_005f0.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_f_005finput_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_f_005finput_005f0 = _jspx_th_f_005finput_005f0.doStartTag();
      if (_jspx_th_f_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_f_005finput_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_f_005finput_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_f_005finput_005f0.doFinally();
      _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_f_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_f_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_f_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ff_005finput_0026_005ftype_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_f_005finput_005f1.setPageContext(_jspx_page_context);
    _jspx_th_f_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fform_005f0);
    // /WEB-INF/views/register.jsp(51,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005finput_005f1.setPath("password");
    // /WEB-INF/views/register.jsp(51,8) null
    _jspx_th_f_005finput_005f1.setDynamicAttribute(null, "type", "password");
    // /WEB-INF/views/register.jsp(51,8) null
    _jspx_th_f_005finput_005f1.setDynamicAttribute(null, "placeholder", "Enter Password Here..");
    // /WEB-INF/views/register.jsp(51,8) null
    _jspx_th_f_005finput_005f1.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_f_005finput_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_f_005finput_005f1 = _jspx_th_f_005finput_005f1.doStartTag();
      if (_jspx_th_f_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_f_005finput_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_f_005finput_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_f_005finput_005f1.doFinally();
      _005fjspx_005ftagPool_005ff_005finput_0026_005ftype_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_f_005finput_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_f_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_f_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_f_005finput_005f2.setPageContext(_jspx_page_context);
    _jspx_th_f_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fform_005f0);
    // /WEB-INF/views/register.jsp(56,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005finput_005f2.setPath("address");
    // /WEB-INF/views/register.jsp(56,8) null
    _jspx_th_f_005finput_005f2.setDynamicAttribute(null, "placeholder", "Enter Address Here..");
    // /WEB-INF/views/register.jsp(56,8) null
    _jspx_th_f_005finput_005f2.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_f_005finput_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_f_005finput_005f2 = _jspx_th_f_005finput_005f2.doStartTag();
      if (_jspx_th_f_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_f_005finput_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_f_005finput_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_f_005finput_005f2.doFinally();
      _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_f_005finput_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_f_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_f_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_f_005finput_005f3.setPageContext(_jspx_page_context);
    _jspx_th_f_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fform_005f0);
    // /WEB-INF/views/register.jsp(61,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005finput_005f3.setPath("email");
    // /WEB-INF/views/register.jsp(61,8) null
    _jspx_th_f_005finput_005f3.setDynamicAttribute(null, "placeholder", "Enter Email Here..");
    // /WEB-INF/views/register.jsp(61,8) null
    _jspx_th_f_005finput_005f3.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_f_005finput_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_f_005finput_005f3 = _jspx_th_f_005finput_005f3.doStartTag();
      if (_jspx_th_f_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_f_005finput_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_f_005finput_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_f_005finput_005f3.doFinally();
      _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_f_005finput_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_f_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_f_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_f_005finput_005f4.setPageContext(_jspx_page_context);
    _jspx_th_f_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fform_005f0);
    // /WEB-INF/views/register.jsp(66,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005finput_005f4.setPath("phone");
    // /WEB-INF/views/register.jsp(66,8) null
    _jspx_th_f_005finput_005f4.setDynamicAttribute(null, "placeholder", "Enter Mobile no. Here..");
    // /WEB-INF/views/register.jsp(66,8) null
    _jspx_th_f_005finput_005f4.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_f_005finput_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_f_005finput_005f4 = _jspx_th_f_005finput_005f4.doStartTag();
      if (_jspx_th_f_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_f_005finput_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_f_005finput_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_f_005finput_005f4.doFinally();
      _005fjspx_005ftagPool_005ff_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_f_005finput_005f4);
    }
    return false;
  }
}
